name: Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  check-files:
    runs-on: ubuntu-latest
    name: Check files changed
    outputs:
      changed-files: ${{ toJSON(steps.changed-files-specific.outputs) }}
      bump-version: ${{ steps.changed-files-specific.outputs.only_changed == 'false' }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v42
        with:
          files: |
            src/**
          files_ignore: |
            !packages/**/*

  release:
    if: needs.check-files.outputs.bump-version == 'true'
    runs-on: ubuntu-latest
    needs:
      - check-files
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^8
          run_install: false

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish package
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          # pnpm -r --filter "./packages/*" --filter "./packages/**/*" exec npm publish --access public --no-git-checks
          pnpm run publish-pkg

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
